### ISSUE TITLE
这里是什么意思

### ISSUE THREAD

**Issue by ratafee1** [1542254356/Contra#2]
https://github.com/1542254356/Contra/blob/877a191b6f0db8951ca20fe05f39d2c912e3d018/Game/Application.cpp#L65

**Comment by ShiningShirley** [comment]
为什么没有敌人

**Comment by philhuan** [comment]
> https://github.com/1542254356/Contra/blob/877a191b6f0db8951ca20fe05f39d2c912e3d018/Game/Application.cpp#L65

上次游戏循环的时间，用static变量存储，如果是第一次，会初始化为当前时间

**Comment by philhuan** [comment]
> 为什么没有敌人

敌人的资源和对象已经有了，自动逻辑还没完善，默认现在没敌人
